export const FETCHING_PRODUCTS_REQUEST = 'FETCHING_PRODUCTS_REQUEST'
export const FETCHING_PRODUCTS_SUCCESS = 'FETCHING_PRODUCTS_SUCCESS'
export const FETCHING_PRODUCTS_FAIL = 'FETCHING_PRODUCTS_FAIL'