export const BUY_MOBILE='BUY_MOBILE'
export const SELL_MOBILE='SELL_MOBILE'

export const USERS_LIST='USERS_LIST'

export const GET_ALL_USERS='GET_ALL_USERS'
export const GET_ALL_USERS_SUCCESS='GET_ALL_USERS_SUCCESS'
export const GET_ALL_USERS_FAIL='GET_ALL_USERS_FAIL'

export const GET_SINGLE_USER='GET_SINGLE_UESR'
export const GET_SINGLE_USER_SUCCESS='GET_SINGLE_UESR_SUCCESS'
export const GET_SINGLE_USER_FAIL='GET_SINGLE_UESR_FAIL'

export const ADD_USER='ADD_UESR'
export const ADD_USER_SUCCESS='ADD_UESR_SUCCESS'
export const ADD_USER_FAIL='ADD_UESR_FAIL'

export const EDIT_USER='EDIT_UESR'
export const EDIT_USER_SUCCESS='EDIT_UESR_SUCCESS'
export const EDIT_USER_FAIL='EDIT_UESR_FAIL'

export const DELETE_USER='DELETE_UESR'
export const DELETE_USER_SUCCESS='DELETE_UESR_SUCCESS'
export const DELETE_USER_FAIL='DELETE_UESR_FAIL'




export const SEND_REQUEST='SEND_REQUEST'
export const SEND_REQUEST_SUCCESS='SEND_REQUEST_SUCCESS'
export const SEND_REQUEST_FAIL='SEND_REQUEST_FAIL'


export const ADD_TODO='ADD_TODO'
export const ADD_TODO_SUCCESS='ADD_TODO_SUCCESS'
export const DELETE_TODO='DELETE_TODO'
export const DELETE_TODO_SUCCESS='DELETE_TODO_SUCCESS'